---
# NGINX HANDLERS
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: nginx config test
  command: nginx -t
