# VARIABLES EQUIPO MONITOREO

# Informaci贸n del equipo
team_info:
  name: "monitoring"
  description: "Equipo especializado en monitoreo y observabilidad"
  emoji: ""

# Configuraci贸n de Prometheus
prometheus_config:
  port: 9090
  retention_time: "30d"
  scrape_interval: "15s"
  evaluation_interval: "15s"
  
# Configuraci贸n de Grafana
grafana_config:
  port: 3000
  admin_user: "admin"
  admin_password: "admin123"
  enable_anonymous: false
  
# Configuraci贸n de alertas
alertmanager_config:
  port: 9093
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  enable_slack: true
  
# Targets a monitorear
monitoring_targets:
  - name: "webserver_ssl_servers"
    port: 9113  # Nginx exporter
    metrics_path: "/metrics"
    
  - name: "security_servers" 
    port: 9114  # Custom security metrics
    metrics_path: "/security-metrics"
    
  - name: "cicd_servers"
    port: 9115  # Jenkins exporter
    metrics_path: "/prometheus"
    
  - name: "traefik_servers"
    port: 8080  # Traefik metrics
    metrics_path: "/metrics"

# Puertos a abrir
firewall_ports:
  - 9090  # Prometheus
  - 3000  # Grafana  
  - 9093  # Alertmanager
  - 9100  # Node exporter
